# Generated by Django 4.2.18 on 2025-07-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_question_delete_post_alter_choice_question_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='question',
        ),
    ]
